version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - vandorjw
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: vue-loader
    versions:
    - 16.1.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: sinon-chai
    versions:
    - 3.5.0
