language: node_js
node_js:
  - node

addons:
  sonarcloud:
    organization: "vandorjw-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN

script:
  - yarn run build
  - sonar-scanner

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
